### ISSUE TITLE
Crash when script fails

### ISSUE THREAD

**Issue by xnoreq** [bpetlert/networkd-broker#2]
Hello,
I just had a crash here https://github.com/bpetlert/networkd-broker/blob/1c55ffdc902fad7dc1567b0975ea94125c28cb5d/src/script.rs#L155 because of the unwrap because there was an error in a script.

Unwrap should be avoided, especially when handling I/O or OS results that can easily fail.
Instead I'd like to see an ERROR log message.

**Comment by bpetlert** [comment]
I released version 0.5.0. It should solve this issue.
I will be waiting for your feedback. :)

**Comment by xnoreq** [comment]
Looked through the code and tested it with a broken script, looks good. Thanks for this and networkd-broker.
