### ISSUE TITLE
Relax log severity

### ISSUE THREAD

**Issue by jmagnuson** [bpetlert/networkd-broker#3]
`networkd-broker`'s README suggests that all event directories should exist, so understandably throws a warning when it receives an event for which it can't find the appropriate directory.

However, it also throws warnings for a directory which does exist, but contains no scripts to run:

```
INFO networkd_broker::broker: Respond to 'no-carrier' event of 'veth8a1ed51'
WARN networkd_broker::broker: Could not get scripts from `/etc/networkd/broker.d/no-carrier.d`: No script in `/etc/networkd/broker.d/no-carrier.d`
```

To me, this feels more like `INFO` or `DEBUG` level information, since even the README's example shows a sparse directory tree.

Happy to throw up a PR, but log levels can be subjective, so interested to hear other thoughts.

**Comment by bpetlert** [comment]
I agree. `WARN` is a little too intimidating in this case . It would be more appropriate to use `INFO`.
I think logging messages need more improvement. Any PR is welcome to improve them.
